
-- 10.	Write a SQL query to retrieve the names and total revenue generated by all customers in the "orders" table,
-- sorted by revenue in descending order, where the customer is from the "USA" and
-- the revenue is greater than the average revenue generated by all customers, and the customer has made at least 2 orders.

USE queries5_3;

SELECT c.Name
       ,SUM(o.Revenue) AS TotalRevenue
--        ,COUNT(o.OrderID) AS TotalOrders
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
WHERE c.Country IN ('USA') 
GROUP BY c.CustomerID 
HAVING 
   TotalRevenue > (SELECT AVG(TotalRevenue) 
     			  FROM (
					SELECT SUM(Revenue) AS TotalRevenue FROM Orders GROUP BY EmployeeID ) 
					AS Temp) 
		   AND 
COUNT(o.OrderID)>2
ORDER BY TotalRevenue DESC;
