-- 9.	Write a SQL query to retrieve the names and total revenue generated by all customers in the "orders" table,
-- sorted by revenue in descending order, where the customer is from the "USA" and the revenue 
-- is greater than the average revenue generated by all customers from the "USA".

USE queries5_3;

SELECT c.Name ,SUM(o.Revenue) AS TotalRevenue
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
WHERE c.Country IN ('USA') 
GROUP BY c.Name
HAVING TotalRevenue > (SELECT AVG(TotalRevenue) 
					   FROM (
                           SELECT SUM(Revenue) AS TotalRevenue 
                           FROM Customers c1
						   JOIN Orders o1 ON c1.CustomerID = o1.CustomerID
						   WHERE c1.Country IN ('USA') 
                           GROUP BY c1.CustomerID) 
					   AS Temp)
ORDER BY TotalRevenue DESC;


