-- 2.	Write a SQL query to retrieve the names and total revenue generated by all customers 
--      in the "orders" table, sorted by revenue in descending order.

SELECT c.Name, SUM(o.Revenue) AS TotalRevenue
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
GROUP BY c.Name
ORDER BY TotalRevenue DESC;
