-- 8.	Write a SQL query to retrieve the names and total revenue generated by all customers in the "orders" table,
-- sorted by revenue in descending order, where the customer is from the "USA" and the revenue is greater than $5,000.

USE queries5_3;

SELECT c.CustomerID, c.Name,  SUM(o.Revenue) AS TotalRevenue
FROM Customers c 
JOIN Orders o ON c.CustomerID = o.CustomerID
WHERE c.Country IN ('USA') 
GROUP BY c.CustomerID
HAVING TotalRevenue> 5000;
-- HAVING TotalRevenue> 15000;

