-- 3.	Write a SQL query to retrieve the names and total revenue generated by all customers 
-- in the "orders" table, sorted by revenue in descending order, where the total revenue is greater than $10,000.
USE queries5_3;

SELECT c.Name, SUM(o.Revenue) AS TotalRevenue
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
GROUP BY c.Name
HAVING TotalRevenue > 10000
ORDER BY TotalRevenue DESC;
